default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: <%= File.read('/run/secrets/db_password').strip rescue 'postgres' %>

development:
  <<: *default
  database: rails_app_development

production:
  <<: *default
  database: rails_app_production
